# Generated by Django 3.0.3 on 2020-04-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='e')),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
