# Generated by Django 3.0.3 on 2020-04-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tv',
            new_name='Products',
        ),
    ]
