# Generated by Django 3.0.3 on 2020-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField(default=None, null=True)),
                ('category', models.CharField(default=None, max_length=500, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('model', models.CharField(max_length=500, null=True)),
                ('article', models.CharField(default=None, max_length=500, null=True)),
                ('url', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='e')),
                ('anotation', models.TextField(default=None, max_length=5000, null=True)),
                ('description', models.TextField(default=None, max_length=20000, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True)),
                ('title_page', models.CharField(default=None, max_length=500, null=True)),
                ('key_word', models.CharField(default=None, max_length=500, null=True)),
                ('page_description', models.CharField(default=None, max_length=500, null=True)),
                ('importer', models.CharField(default=None, max_length=500, null=True)),
                ('servise_centre', models.CharField(default=None, max_length=500, null=True)),
                ('make', models.CharField(default=None, max_length=500, null=True)),
                ('garancy', models.CharField(default=None, max_length=10, null=True)),
                ('img_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tv',
        ),
    ]
