# Generated by Django 3.0.3 on 2020-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200505_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_id',
            field=models.IntegerField(null=True),
        ),
    ]
